import { Geist, Geist_Mono } from "next/font/google";

import Header from '../../components/Header';
import Footer from '../../components/Footer';
import "@fortawesome/fontawesome-free/css/all.min.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "National Association of Dog Obedience Instructors",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Header />
      <main data-bs-header-fixed="true">
        {children}
      </main>
      <Footer />
    </>
  );
}
