import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import { ToastContainer, Slide } from "react-toastify";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "National Association of Dog Obedience Instructors",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ToastContainer position="top-right" theme="dark" transition={Slide} />
                {children}
            </body>
        </html>
    );
}
